Feature/contact
6karai9/oh-my-donut pull request #47
Opened 2021-05-16 19:46 UTC by litrekin

Fixed _contact.scss

2021-05-16 20:30 UTC, 6karai9 requested changes

2021-05-16 20:30 UTC, 6karai9 commented on src/partials/contact.html
> +<!DOCTYPE html>
тебе не нужно прописывать DOCTYPE, он у нас есть уже в главном index.html

2021-05-16 20:30 UTC, 6karai9 commented on src/partials/contact.html
> +    <section>
сначала идет `<section>` а после него все остальное, а у тебя `<div>` выше чем section, поставь первым section

2021-05-16 20:30 UTC, 6karai9 commented on src/sass/layouts/_contact.scss
> +.title {
у нас этот класс в общих стилях прописан, посмотри в common.scss

2021-05-16 20:30 UTC, 6karai9 commented on src/sass/layouts/_contact.scss
> +  font-family: Caveat Brush, sans-serif;
у нас есть общий стиль для кнопок button-style, используй его

2021-05-17 04:51 UTC, closed without merging

2021-05-17 05:03 UTC, litrekin commented on src/partials/contact.html
> +<!DOCTYPE html>
Его нужно т.к. у меня пишет ошибка постоянно